#!/bin/bash


#Used for intial setup of the environment , to be typed in every new terminal before running any code





export ROS_HOSTNAME=localhost
export ROS_MASTER_URI=http://localhost:11311
export ROS_PORT_SIM=11311
export GAZEBO_RESOURCE_PATH=~/DRL-robot-navigation/catkin_ws/src/multi_robot_scenario/launch

source ~/.bashrc

cd ~/DRL-robot-navigation/catkin_ws
source devel_isolated/setup.bash

echo "ROS environment setup complete!"
